# Generated by Django 6.1.1 on 2026-09-07 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_productoservicio_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoservicio',
            name='slug',
            field=models.SlugField(auto_created=True, unique=True, verbose_name='Slug URL'),
        ),
    ]
