# Generated by Django 6.1.1 on 2026-09-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_alter_productoservicio_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoservicio',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='SKU (Código de Producto)'),
        ),
    ]
