# Generated by Django 6.1.1 on 2026-09-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_productoservicio_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Teléfono de contacto (colocar con código de país, ej: 51987654321)'),
        ),
        migrations.AlterField(
            model_name='productoservicio',
            name='slug',
            field=models.SlugField(auto_created=True, max_length=255, unique=True, verbose_name='Slug URL (se llena en automático)'),
        ),
    ]
